### ISSUE TITLE
Login, Register and logout ?

### ISSUE THREAD

**Issue by Amine-Smahi** [NikiforovAll/keycloak-authorization-services-dotnet#102]
Hi, 
i wonder how i can do Login, Register and logout,
Is there a documentation for that ?

Thank you

**Comment by NikiforovAll** [comment]
I've added an example to the docs: https://nikiforovall.github.io/keycloak-authorization-services-dotnet/examples/web-app-mvc.html

ref: https://github.com/NikiforovAll/keycloak-authorization-services-dotnet/issues/98

**Comment by NikiforovAll** [comment]
NB, It is front-channel logout
