### ISSUE TITLE
Configuration error

### ISSUE THREAD

**Issue by belarmino** [NikiforovAll/keycloak-authorization-services-dotnet#11]
When i try to access a endpoint with **[Authorize]** annotation, i got error "IDX20803: Unable to obtain configuration from: 'System.String'".

Configuration in program.cs
```console
    builder.Host.ConfigureKeycloakConfigurationSource();

    builder.Services.AddKeycloakAuthentication(builder.Configuration, o =>
    {
        o.RequireHttpsMetadata = false;
    });

    app.UseAuthentication();
    app.UseAuthorization();
```
Bellow is my keycloack config
```console
{
    "realm": "xpro-realm",
    "auth-server-url": "http://localhost:8082/auth/",
    "ssl-required": "external",
    "resource": "xpto-backend",
    "credentials": {
        "secret": "xpto-xpto-xpto-xpto-xpto"
    },
    "confidential-port": 0
}
```

**Comment by NikiforovAll** [comment]
Could you please provide the version of the package? The provided configuration should be for 1.3.0

**Comment by belarmino** [comment]
I have used 1.2.0, i will change to 1.3.0.

**Comment by NikiforovAll** [comment]
Ah, yes. Make sure the keycloak.json is copied to build output. 

ref: https://stackoverflow.com/questions/12384628/msbuild-copy-file-after-build

**Comment by alwo23** [comment]
The problem seems to be the inconsistent attributing of the properties in the `KeycloakInstallationOptions` in connection with the re-writting of the configuration in `KeycloakConfigurationProvider.NormalizeKey`.
In a hurry, we came up with this quick and dirty work-around:

- We removed `host.ConfigureKeycloakConfigurationSource()` and instead 
- added a manually re-written _keycloak.json_ as just another JSON configuration file
  Our keycloak.json now looks like this:
  ```json
  {
    "Keycloak": {
      "Realm": "...",
      "auth-server-url": "...",
      "ssl-required": ... ,
      "Resource": "...",
      "verify-token-audience": ... ,
      "UseResourceRoleMapping: ... ,
      "ConfidentialPort": ... 
    }
  }
  ```

**Comment by NikiforovAll** [comment]
The configuration file doesn't work because you must copy it during build time.  This is not done by default so you need to right-click on file > properties > 
![image](https://user-images.githubusercontent.com/8037439/191766207-a48b08a8-251b-46ce-9cd9-c18d943734a3.png)

**Comment by NikiforovAll** [comment]
By the way, the `1.2.1` version is supposed to handle PascalCase and snake-case for configuration.

**Comment by NikiforovAll** [comment]
Note, the properties below are essentially ignored in the current implementation and this is something can add 

``` text
    "UseResourceRoleMapping": true,
    "ConfidentialPort": 123 
```

**Comment by alwo23** [comment]
> Hey @alwo23,
> 
> The configuration file doesn't work because you must copy it during build time. This is not done by default so you need to right-click on file > properties > ![image](https://user-images.githubusercontent.com/8037439/191766207-a48b08a8-251b-46ce-9cd9-c18d943734a3.png)

Of course, this is NOT the problem, because we did get some configurations, but not so, so the file was copy to the output directory ...

**Comment by alwo23** [comment]
> By the way, the `1.2.1` version is supposed to handle PascalCase and snake-case for configuration.
> 
> So both approaches should work:
> 
>     1. keycloak.json + build to output (this part is important and gives you the error ⚠)
> 
> 
> ```json
> {
>   "realm": "xpro-realm",
>   "auth-server-url": "http://localhost:8082/auth/",
>   "ssl-required": "external",
>   "resource": "",
>   "credentials": {
>     "secret": ""
>   }
> }
> ```
> 
>     2. appsettings.{Env}.json
> 
> 
> ```json
> {
>   "Keycloak": {
>     "Realm": "xpro-realm",
>     "AuthServerUrl": "http://localhost:8082/auth/",
>     "SslRequired": "external",
>     "Resource": "",
>     "Credentials": {
>       "Secret": ""
>     }
>   }
> }
> ```
> 
> And also,
> 
> ```json
> {
>   "Keycloak": {
>     "realm": "xpro-realm",
>     "auth-server-url": "http://localhost:8082/auth/",
>     "ssl-required": "external",
>     "resource": "",
>     "credentials": {
>       "secret": ""
>     }
>   }
> }
> ```

Yes, I found v1.2.1 shortly after posting my initial comment here and it does fix the problem. THX!

**Comment by alwo23** [comment]
> Note, the properties below are essentially ignored in the current implementation and this is something can add
> 
> ```
>     "UseResourceRoleMapping": true,
>     "ConfidentialPort": 123 
> ```

Yes, we saw the in your code, but we do not need this setting (so far?).

**Comment by NikiforovAll** [comment]
@alwo23 , yeah, for basic scenarios we don't really need this one, but If you want to include these settings, please feel free to contribute.
