### ISSUE TITLE
Support for Keycloak 24.0.4

### ISSUE THREAD

**Issue by eramosr16** [NikiforovAll/keycloak-authorization-services-dotnet#110]
I recently upgraded my Keycloak to version 24.0.4 and using:

`<PackageReference Include="Keycloak.AuthServices.Authentication" Version="2.4.1" />
    <PackageReference Include="Keycloak.AuthServices.Authorization" Version="2.4.1" />
    <PackageReference Include="Keycloak.AuthServices.Sdk" Version="2.4.1" />`

Now I'm getting constant Unauthorized errors calling to get a user information

**Comment by NikiforovAll** [comment]
Hi Ernesto,

Please refer to
https://nikiforovall.github.io/keycloak-authorization-services-dotnet/migration.html
for the migration guide, it contains breaking changes. Also, we can set
up a quick call so I can help you with migration.

Kind Regards
Oleksii
