### ISSUE TITLE
While adding AddKeycloakAuthorization something crashes.

### ISSUE THREAD

**Issue by imecar-github** [NikiforovAll/keycloak-authorization-services-dotnet#116]
Hello I am facing this issue for all of the samples that includes services.AddKeycloakAuthorization

![image](https://github.com/NikiforovAll/keycloak-authorization-services-dotnet/assets/98873869/6cb30a37-e618-49e8-8977-9bff0d2847c5)

Details in below

`System.AggregateException
  HResult=0x80131500
  Message=Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: Microsoft.AspNetCore.Authorization.IAuthorizationService Lifetime: Transient ImplementationType: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService': Unable to resolve service for type 'System.Diagnostics.Metrics.IMeterFactory' while attempting to activate 'Keycloak.AuthServices.Authorization.KeycloakMetrics'.) (Error while validating the service descriptor 'ServiceType: Microsoft.AspNetCore.Authorization.IAuthorizationHandlerProvider Lifetime: Transient ImplementationType: Microsoft.AspNetCore.Authorization.DefaultAuthorizationHandlerProvider': Unable to resolve service for type 'System.Diagnostics.Metrics.IMeterFactory' while attempting to activate 'Keycloak.AuthServices.Authorization.KeycloakMetrics'.) (Error while validating the service descriptor 'ServiceType: Microsoft.AspNetCore.Authorization.Policy.IPolicyEvaluator Lifetime: Transient ImplementationType: Microsoft.AspNetCore.Authorization.Policy.PolicyEvaluator': Unable to resolve service for type 'System.Diagnostics.Metrics.IMeterFactory' while attempting to activate 'Keycloak.AuthServices.Authorization.KeycloakMetrics'.) (Error while validating the service descriptor 'ServiceType: Microsoft.AspNetCore.Authorization.IAuthorizationHandler Lifetime: Singleton ImplementationType: Keycloak.AuthServices.Authorization.Requirements.RealmAccessRequirementHandler': Unable to resolve service for type 'System.Diagnostics.Metrics.IMeterFactory' while attempting to activate 'Keycloak.AuthServices.Authorization.KeycloakMetrics'.) (Error while validating the service descriptor 'ServiceType: Microsoft.AspNetCore.Authorization.IAuthorizationHandler Lifetime: Singleton ImplementationType: Keycloak.AuthServices.Authorization.Requirements.ResourceAccessRequirementHandler': Unable to resolve service for type 'System.Diagnostics.Metrics.IMeterFactory' while attempting to activate 'Keycloak.AuthServices.Authorization.KeycloakMetrics'.) (Error while validating the service descriptor 'ServiceType: Keycloak.AuthServices.Authorization.KeycloakMetrics Lifetime: Singleton ImplementationType: Keycloak.AuthServices.Authorization.KeycloakMetrics': Unable to resolve service for type 'System.Diagnostics.Metrics.IMeterFactory' while attempting to activate 'Keycloak.AuthServices.Authorization.KeycloakMetrics'.)
  Source=Microsoft.Extensions.DependencyInjection
  StackTrace:
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(ICollection`1 serviceDescriptors, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, ServiceProviderOptions options)
   at Microsoft.Extensions.Hosting.HostApplicationBuilder.Build()
   at Microsoft.AspNetCore.Builder.WebApplicationBuilder.Build()
   at Program.<Main>$(String[] args) in C:\Users\Arge13\source\repos\WebApi1\WebApi1\Program.cs:line 40

  This exception was originally thrown at this call stack:
    Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceIdentifier, System.Type, Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteChain, System.Reflection.ParameterInfo[], bool)
    Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(Microsoft.Extensions.DependencyInjection.ServiceLookup.ResultCache, Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceIdentifier, System.Type, Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteChain)
    Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Microsoft.Extensions.DependencyInjection.ServiceDescriptor, Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceIdentifier, Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteChain, int)
    Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceIdentifier, Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteChain)
    Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceIdentifier, Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteChain)
    Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceIdentifier, Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteChain)
    Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceIdentifier, System.Type, Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteChain, System.Reflection.ParameterInfo[], bool)
    Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(Microsoft.Extensions.DependencyInjection.ServiceLookup.ResultCache, Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceIdentifier, System.Type, Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteChain)
    Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Microsoft.Extensions.DependencyInjection.ServiceDescriptor, Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceIdentifier, Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteChain, int)
    Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateEnumerable(Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceIdentifier, Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteChain)
    ...
    [Call Stack Truncated]

Inner Exception 1:
InvalidOperationException: Error while validating the service descriptor 'ServiceType: Microsoft.AspNetCore.Authorization.IAuthorizationService Lifetime: Transient ImplementationType: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService': Unable to resolve service for type 'System.Diagnostics.Metrics.IMeterFactory' while attempting to activate 'Keycloak.AuthServices.Authorization.KeycloakMetrics'.

Inner Exception 2:
InvalidOperationException: Unable to resolve service for type 'System.Diagnostics.Metrics.IMeterFactory' while attempting to activate 'Keycloak.AuthServices.Authorization.KeycloakMetrics'.
`

If I want to run samples I got this error too, 

Target Framework : .NET 7.0

**Comment by NikiforovAll** [comment]
Thank you for reporting this issue,  I wasn't able to reproduce it locally, but this fix should do
