### ISSUE TITLE
Add support for the GET /admin/realms/{realm}/users/count endpoint in the Admin API SDK

### ISSUE THREAD

**Issue by kanpov** [NikiforovAll/keycloak-authorization-services-dotnet#118]
**Why is this needed:** In order to determine, for example, the total amount of users in the system, which is crucial for pagination (whether there is a next page or a previous page, how many items in total etc.)

Referring to the Admin API documentation for version 25.0.0 of Keycloak, this is the endpoint:
![image](https://github.com/NikiforovAll/keycloak-authorization-services-dotnet/assets/71177577/21212a5d-66c1-4184-accf-4fe89af50945)

**Comment by kanpov** [comment]
@NikiforovAll Made a proposal to add this endpoint in PR #120

**Comment by NikiforovAll** [comment]
Thank you for your contribution. Do you need this one, should I release the version/pre-release version?

**Comment by kanpov** [comment]
> Thank you for your contribution. Do you need this one, should I release the version/pre-release version? 

Yes, one of my projects currently needs user pagination which is why I contributed this. I'm planning on doing more endpoints, but later
