### ISSUE TITLE
Multi Realm Authentication

### ISSUE THREAD

**Issue by Azzahid** [NikiforovAll/keycloak-authorization-services-dotnet#122]
Hi guys,

Currently I face a problem where I need to authenticate JWT token from 2 different realm in one gateway. Currently my company is using this library to handle authentication process of the token, but from what I read it only handle 1 configuration for 1 authentication. 

Is there a way to handle multi realm using this library ? If not do you guys have a suggestion how I can implement this ?

**Comment by NikiforovAll** [comment]
It is not supported out of the box, but you could try something like following:

https://github.com/NikiforovAll/keycloak-authorization-services-dotnet/discussions/123#discussioncomment-9881517

**Comment by Azzahid** [comment]
Thank you, I'll try to implement it.
