### ISSUE TITLE
consider using quay.io/keycloak/keycloak as the keycloak container

### ISSUE THREAD

**Issue by dustyroberts** [NikiforovAll/keycloak-authorization-services-dotnet#13]
quay.io/keycloak/keycloak appears to be more up to date with the latest keycloak version.

You will notice some slight changes in the keycloak.json file.

**Comment by NikiforovAll** [comment]
we can implement a global switch 
`KeycloakSwitch.SetCompatabilityVersion("JBoss" | "Quay", "...")`

**Comment by NikiforovAll** [comment]
Closing as obsolete
