### ISSUE TITLE
WebApp support for PKCE?

### ISSUE THREAD

**Issue by VictorioBerra** [NikiforovAll/keycloak-authorization-services-dotnet#134]
Hello, I do not want to use implicit flow, and instead use the newer and more secure PKCE flow.

How do I set the response type to code and enable PKCE in my config, and with `builder.Services.AddKeycloakWebAppAuthentication(builder.Configuration);`

**Comment by NikiforovAll** [comment]
Hello @VictorioBerra ,

There is an overload that takes `OpenIdConnectOptions` 

https://nikiforovall.github.io/keycloak-authorization-services-dotnet/configuration/configuration-authentication.html#authenticationbuilder-extensions-%F0%9F%9A%A7

```csharp
builder.Services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
    .AddKeycloakWebApp(
        configureKeycloakOptions: options =>
        {
            builder.Configuration.GetSection(KeycloakAuthenticationOptions.Section).Bind(options);
        },
        configureOpenIdConnectOptions: options =>
        {
            // Other code omitted for brevity...

            options.UsePkce = true;
            // probably you need to add other configurations to make it work
            
            // Other code omitted for brevity...
        }
    );
```

**Comment by VictorioBerra** [comment]
That worked.

I am trying to see what else is needed, @NikiforovAll can you link me to what OpenIdConnectOptions are already set?

For example, Duende sample clients set these: https://github.com/DuendeSoftware/IdentityServer/blob/main/clients/src/MvcCode/Startup.cs

For example, is `GetClaimsFromUserInfoEndpoint` true when using `AddKeycloakWebApp`?

**Comment by NikiforovAll** [comment]
@VictorioBerra  https://github.com/NikiforovAll/keycloak-authorization-services-dotnet/blob/main/src/Keycloak.AuthServices.Authentication/WebAppExtensions/KeycloakWebAppAuthenticationBuilderExtensions.cs#L242
