### ISSUE TITLE
web examples for redirection

### ISSUE THREAD

**Issue by Polemus** [NikiforovAll/keycloak-authorization-services-dotnet#14]
Is there any chance you can give an example of how to set all the options when when it comes to redirecting to keycloak for user authenication on a web page.

i know with OIDC you set the authentication url, the redirect url etc, but i cant seem to find these using your middleware.

**Comment by NikiforovAll** [comment]
It is something that I would like to implement once I have time. Particularly, I'm interested in the Blazor WASM scenario. But I'm not sure if I have time to do it in the near future.

**Comment by NikiforovAll** [comment]
@Polemus please see: https://nikiforovall.github.io/blazor/dotnet/2022/12/08/dotnet-keycloak-blazorwasm-auth.html
