### ISSUE TITLE
Possible to set realm per request?

### ISSUE THREAD

**Issue by tylerje** [NikiforovAll/keycloak-authorization-services-dotnet#15]
I want to set the realm on request based on the domain name in the request in order to host multiple customers with vanity domain names on the same host but with different realm/users for each.

Is that possible and how would it be done?

**Comment by NikiforovAll** [comment]
Hi @tylerje ,

Could you please provide more details?

I assume you want to authenticate users from different realms. It is a supported scenario. 

Selecting different authentication configurations in runtime is not supported and it could be achieved by introducing different authentication schemes.

For example, we can create different clients (which can be found in the primary sidebar) for different realms. Then, configure authentication schemes for each client and select them dynamically based on middleware. 

The best option is to investigate the source code and adjust it according to your needs.

https://github.com/NikiforovAll/keycloak-authorization-services-dotnet/blob/main/src/Keycloak.AuthServices.Authentication/ServiceCollectionExtensions.cs#L39-L51

**Comment by tylerje** [comment]
Thanks, @NikiforovAll
