### ISSUE TITLE
Add .NET 8 support to samples projects

### ISSUE THREAD

**Issue by LLDevLab** [NikiforovAll/keycloak-authorization-services-dotnet#150]
Change target framework in projects from .NET 6 to .NET 8 or add it as second target framework.

**Comment by LLDevLab** [comment]
@NikiforovAll What do you think, would it be ok to change target framework of all projects to .NET8 and update nuget packaegs to latest stable version?

**Comment by NikiforovAll** [comment]
This is great idea

**Comment by NikiforovAll** [comment]
Please feel free to update sample apps and dependencies. 

Ref: https://github.com/NikiforovAll/keycloak-authorization-services-dotnet/pull/148

**Comment by LLDevLab** [comment]
@NikiforovAll sorry, my bad. I've checked Visual Studio nuget search and for some reason it do not show references to .NET8:

![Keycloak](https://github.com/user-attachments/assets/14a2e4c2-6c3e-4d33-b00c-94f653ada3b6)

But in nuget.org reference exists. Will update sample apps.
