### ISSUE TITLE
There are some plans to Update projecto .NET9?

### ISSUE THREAD

**Issue by fmattioli** [NikiforovAll/keycloak-authorization-services-dotnet#157]
![image](https://github.com/user-attachments/assets/b918b114-df70-4561-aa36-e9b49ff1707b)
I am with this warning on my project.
Looks like the reason to that is the package System.Text.Json.
Package 'System.Text.Json' 8.0.0 has a known high severity vulnerability, https://github.com/advisories/GHSA-hh2w-p6rv-4g7w

**Comment by NikiforovAll** [comment]
This is a good idea, I plan to work on it
