### ISSUE TITLE
User management in Keycloak.AuthServices.Sdk

### ISSUE THREAD

**Issue by victor-borges** [NikiforovAll/keycloak-authorization-services-dotnet#19]
Hi, first of all thank you for this great and neat package!

I'm using the authentication and authorization packages right now, and there's a need here for user management using the REST API (and I would gladly contribute it as a PR) but I have some questions about the purpose of the `Keycloak.AuthServices.Sdk` right now. Is it supposed to (or aspire to) be a one-stop shop for Keycloak administration? Or is it more in a supporting role for the Authentication and Authorization packages?
Really want to see your thoughts on this, because I couldn't find very good alternatives out there for a (modern) Keycloak REST API client in C#.

**Comment by NikiforovAll** [comment]
Hi @victor-borges ,

> the purpose of the Keycloak.AuthServices.Sdk right now. Is it supposed to (or aspire to) be a one-stop shop for Keycloak administration?

Yes, it is!

---

It would be great to extend REST API integration, there is already API for realm management and we can elaborate and implement the missing part of the management API integration

**Comment by NikiforovAll** [comment]
It should be easy to implement, I didn't have time to bring the API surface gap, but we can do it together. 🙂

**Comment by victor-borges** [comment]
I'm working on it right now, I could open a draft PR for the discussion as well, what do you think?

**Comment by NikiforovAll** [comment]
That would be perfect, let me know if you want a 15-30 min kick-off or discussion during a call
