### ISSUE TITLE
Receiving JWT Token.

### ISSUE THREAD

**Issue by DTeuchert** [NikiforovAll/keycloak-authorization-services-dotnet#21]
In my application I have a custom login page, at this I call `await _httpClient.RequestPasswordTokenAsync(new PasswordTokenRequest(...));` for receiving a JWT token. 

At this function I also need to provice oidc information. In order to reduce double configuration, is there an similar function available?

How do I set these token into the `HttpContext.SignInAsync()` funtion to use the IdentityUser model?

**Comment by NikiforovAll** [comment]
The suggested scenario is not supported, the identity is populated from access_token 

Here is how to read Keycloak configuration:

```csharp
KeycloakAuthenticationOptions options = new();

        configuration
            .GetSection(KeycloakAuthenticationOptions.Section)
            .Bind(options, opt => opt.BindNonPublicProperties = true);
```
---

From a design perspective, implementing a custom login page on the Keycloak side is the way to go.
