### ISSUE TITLE
Markdown table with packages is not displayed correctly on Nuget.org

### ISSUE THREAD

**Issue by NikiforovAll** [NikiforovAll/keycloak-authorization-services-dotnet#25]
E.g: https://www.nuget.org/packages/Keycloak.AuthServices.Authorization

![image](https://user-images.githubusercontent.com/8037439/212830764-4c7fc5ef-dc01-4eea-8fa8-d4b1cb605355.png)

**Comment by NikiforovAll** [comment]
Hi @victor-borges ,

We've introduced minor regression issues somewhere between 1.3.0 and 1.5.0. Could you please take a look? It might be hard to reproduce it on your side, but it would be great if you take a look. Thanks!

**Comment by victor-borges** [comment]
Hi, I'll take a look
