### ISSUE TITLE
Not working as expected -or- I don't get it...

### ISSUE THREAD

**Issue by Neuroquila-n8fall** [NikiforovAll/keycloak-authorization-services-dotnet#29]
I tried the samples but either I am expecting something completely different or it just doesn't work.
Take the minimal API example: If I access an endpoint it just throws me a 401 but no auth redirect, no nothing. Shouldn't the middleware take care of that already?

The same is true for all other example projects. If I try to implement it myself I get the same result.

**Comment by NikiforovAll** [comment]
It is the default behavior for Web API, the library is built to support the Web API in mind, so if you want to develop some MVC application with redirects and everything you need to override the default and add additional authentication schemas.

**Comment by Neuroquila-n8fall** [comment]
Right.... I assumed that at some point. But then again when I run the most basic identity setup with keycloak the middleware takes care of redirects. When I try the examples (not the API one) I don't get redirected even though the controller setup suggests that something along those lines should happen.

I mean this is a great project and I learned a lot about keycloak specific things while browsing the source but I don't really get how to benefit from the effort you put in as a whole when using it as a package. Maybe if you could provide a small example on how to just integrate with keycloak and have the default identity behavior set up, that would be great since, again, I cannot see it working with the included examples as a custom implementation of a specific identity provider should behave.

The default and expected behavior should be that at any point when an endpoint of any sort is accessed, which is decorated with the `[Authorize]` attribute, the middleware should perform a redirect to the login page, when the user returns and does not have the correct permissions, a 401 should be returned.

**Comment by NikiforovAll** [comment]
Yeah, it is something that we could do once I have time. I have an example of how to setup Keycloak + SPA-like application  (Blazor WASM)

I guess you want to see an example of how to use and configure Keycloak + MVC

**Comment by Neuroquila-n8fall** [comment]
oh i know that problem too well... take your time ;)

**Comment by Kingside88** [comment]
Hi there,

I provide a free demo instance of keycloak: https://keycloak.nicedemo.de/
you can login with admin-admin.
It would be great if you could show us an example there. Best thanks for your'e great work.
If someone is interested, I created a nuxt 3 and vue 3 repo with keycloak authentification
https://github.com/Kingside88/nuxt3-primevue-starter-auth
