### ISSUE TITLE
Could not load file or assembly 'IdentityModel, Version=5.2.0.0, Culture=neutral, PublicKeyToken=e7877f4675df049f'. The system cannot find the file specified.

### ISSUE THREAD

**Issue by igmonius** [NikiforovAll/keycloak-authorization-services-dotnet#30]
Hey !

I've just started looking into your library, but there is a weird bug stopping me, which occurs when I try to invoke any endpoint decorated with an Authorize attribute that was supposed to be handled by a ProtectedResource handler:

![image](https://user-images.githubusercontent.com/16864946/222759854-326962b8-9dbe-44ee-8cea-d5ac577b7b67.png)

I'm running a .NET 7.0 based application, with both Keycloak.AuthServices.Authentication and Keycloak.AuthServices.Authentication being on 1.5.1 version. 

This is how my service registration looks like:

![image](https://user-images.githubusercontent.com/16864946/222760865-564c4af4-fd8e-445e-a516-cc67bb34e52d.png)

This is my Keycloak configuration:

![image](https://user-images.githubusercontent.com/16864946/222761795-b5b2b853-3b2d-40ab-b598-cb1bcec925c9.png)

And this is what I am trying to do:

![image](https://user-images.githubusercontent.com/16864946/222762510-cf0a0f89-7f0b-47df-ab66-7a400b6302f6.png)
![image](https://user-images.githubusercontent.com/16864946/222762604-ab4508e5-d27a-4b28-a6ad-a9d3a05604a2.png)

Thanks in advance !

**Comment by kirides** [comment]
Also happens here, we're forced to add this to our services or they just break
```xml
<PackageReference Include="IdentityModel.AspNetCore" Version="4.3.0" />
```

**Comment by bakgaard** [comment]
@kirides - did you get around it?

**Comment by Nizio-Dev** [comment]
The error is still here.

**Comment by NikiforovAll** [comment]
Expected to be fixe in https://github.com/NikiforovAll/keycloak-authorization-services-dotnet/releases/tag/2.0.0
