### ISSUE TITLE
Role-Based Permission Causes UMA-Ticket Grant to Fail

### ISSUE THREAD

**Issue by coreyperkins** [NikiforovAll/keycloak-authorization-services-dotnet#31]
Even with the default js policy when I add a resource and link it to a Role-based permission I can no longer make use of the KeycloakProtectionClient. I have tried to debug and the decision comes back as false everytime. Additionally, I changed the code to have "response_mode" of type "permissions" so that I can see the result and it returns: "{"error":"access_denied","error_description":"not_authorized"}". I can call the Admin Api and get my resources/scopes just fine, but that is a hack that will not scale.

[Archive.zip](https://github.com/NikiforovAll/keycloak-authorization-services-dotnet/files/11127570/Archive.zip)

I feel like there is an appropriate way to stack permissions such that when the call is made to get a list of resources for the client in VerifyAccessToResource it will return everything the client can do when response_type permissions is provided and it will properly validate when response_type decision is provide but I can't seem to get anywhere.

Thanks ahead of any advice / help. The Scopes, Resources, Policies, Permissions, and Roles are attached.

Corey

**Comment by JimHume** [comment]
Disclaimer: I am not associated with the project in any way.

I recently hit this issue when trying to use the library for a combination of API + UI purposes.

In my case, I was manually adding the protection client to the service collection on startup, but had not added the follow-up call to [.AddHeaderPropagation()](https://github.com/NikiforovAll/keycloak-authorization-services-dotnet/blob/main/src/Keycloak.AuthServices.Sdk/HttpMiddleware/AccessTokenPropagationExtensions.cs#L16). 

You may want to check to ensure your headers contain the appropriate tokens from the client and / or that the http context is impersonating the current user as expected.

**Comment by NikiforovAll** [comment]
Closing as outdated
