### ISSUE TITLE
Feature: add group admin and UMA policy/permission

### ISSUE THREAD

**Issue by JimHume** [NikiforovAll/keycloak-authorization-services-dotnet#35]
As a user of this library I desire the ability to:

- Create and manage groups and their children
- Manage membership to groups
- Use the UMA features of Keycloak from a server on behalf of a user (especially policies and permissions)
- Obtain permission tickets specific to any resource on behalf of a user

When using this library in a larger project that has both a Blazor server app and REST API app it is ideal to have the ability to manage users, groups, their resources, and the policies & permissions associated with all of it. The spirit of this feature is to extend the existing functionality to include other admin API functions and broaden the usage of UMA resources.

**Comment by NikiforovAll** [comment]
Hey @JimHume , 

Thank you for your contribution. I plan to review it in the nearest future.

**Comment by NikiforovAll** [comment]
Added to, thank you for the contribution

https://github.com/NikiforovAll/keycloak-authorization-services-dotnet/releases/tag/2.0.0
