### ISSUE TITLE
Missing execute-actions-email endpoint on users 

### ISSUE THREAD

**Issue by eramosr16** [NikiforovAll/keycloak-authorization-services-dotnet#37]
Missing **execute-actions-email**

https://www.keycloak.org/docs-api/21.1.1/rest-api/index.html
`PUT /{realm}/users/{id}/execute-actions-email`

**Comment by NikiforovAll** [comment]
Hi @eramosr16 ,

Please feel free to contribute. I accept MRs 👍

**Comment by eramosr16** [comment]
I will thanks for letting me know. Best
