### ISSUE TITLE
Make it easier to add new Admin API implementations

### ISSUE THREAD

**Issue by agross** [NikiforovAll/keycloak-authorization-services-dotnet#40]
I needed to implement group querying for my project. For this some internal members required duplication, which is unfortunate.

The setup part:

```csharp
    // This one supports users.
    services.AddKeycloakAdminHttpClient(builder.Configuration);

    // Duplicated:
    KeycloakAdminClientOptions keycloakOptions = new();
    builder.Configuration
           .GetSection(KeycloakAdminClientOptions.Section)
           .Bind(keycloakOptions);

    // This adds group support.
    services.AddRefitClient<IKeycloakGroupClient>(
      // Duplicated.
      new RefitSettings
            {
              ContentSerializer =
                new SystemTextJsonContentSerializer(new JsonSerializerOptions(JsonSerializerDefaults.Web)
                {
                  DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
                }),
            })
            .ConfigureHttpClient(client =>
            {
              var baseUrl = new Uri(keycloakOptions.AuthServerUrl.TrimEnd('/'));
              client.BaseAddress = baseUrl;
            })
            .AddClientAccessTokenHandler("keycloak_admin_api");
```

The implementation:

```csharp
/// <summary>
///   User management
/// </summary>
[Headers("Accept: application/json")]
public interface IKeycloakGroupClient
{
   // Duplicated: I could have used KeycloakClientApiConstants.GetRealm, but it is internal.
  [Get("/admin/realms/{realm}/groups")]
  Task<IEnumerable<Group>> GetGroups(string realm, [Query] GetGroupsRequestParameters? parameters = default);
}
```

**Comment by agross** [comment]
Hello @NikiforovAll,

I understood the idea of registering one façade interface for a number of resource-specific interfaces.

My point was another, though. Since the Admin API has more stuff than is currently implemented by `IKeycloak*Client`s, I think other people will try to add new interfaces targeting those not-yet-supported Admin APIs, as I did with groups. Since those implementations will undoubtedly use the same Refit settings and the same base URL as the currently supported Admin APIs, I think more types should be public to allow for such reuse.

**Comment by NikiforovAll** [comment]
Could you please list the types you want to make public? 

Regarding, Refit settings, they are specified only once and we don't really need them for every client based on the facade approach.

**Comment by agross** [comment]
* `KeycloakClientApiConstants.GetRealm`
* > Regarding, Refit settings, they are specified only once and we don't really need them for every client based on the facade approach.

  Since custom APIs won't be using the façade approach (limitation of C# that you cannot dynamically extend interfaces), I guess custom API implementers would also need that.

I'd like to be able to just maintain this piece of code:

```csharp
[Headers("Accept: application/json")]
public interface IKeycloakGroupClient
{
  [Get("{KeycloakClientApiConstants.GetRealm}/groups")]
  Task<IEnumerable<Group>> GetGroups(string realm, [Query] GetGroupsRequestParameters? parameters = default);
}

// This one supports users and some other APIs.
services.AddKeycloakAdminHttpClient(builder.Configuration);

// This adds group support.
services.AddRefitClient<IKeycloakGroupClient>(KeycloakAdminApi.DefaultRefitSettings);
```

**Comment by NikiforovAll** [comment]
From my point of view, it would be perfectly fine to contribute the missing parts of the API to the library itself. It is also an option to expose configuration as you mentioned, but I don't really think we should have a concept of custom API since the Keycloak itself has a well-defined API. We could just implement it :)

**Comment by agross** [comment]
> it would be perfectly fine to contribute the missing parts of the API

I totally agree and I'll do that once I support child groups.

> I don't really think we should have a concept of custom API

I was not implying that you should. My point was to make it easier for people to start with a new API outside of this library and give them the option to contribute back (if they're allowed to).

The side-effect of making a few things public will be that new APIs contributed in this way will be battle-tested. Also contributors do not need to change their code when contributing back because there is no duplication required (that would be removed once integrated here).

**Comment by NikiforovAll** [comment]
Looking forward to your contribution. 

Certainly, an interesting idea to expose some parts of the configuration to the outside world. But I think keeping things `private` would encourage people to contribute to the library itself.
