### ISSUE TITLE
Keycloak configuration for external and internal Authentication

### ISSUE THREAD

**Issue by VentsislavDinev** [NikiforovAll/keycloak-authorization-services-dotnet#42]
Hello, 
I want to develop SaaS with ASP.NET and Keycloak authentication and authorization.
How to configure Keycloak-Authorization-Services-Dotnet for access from external customer.
How to configure Keycloak-Authorization-Services-Dotnet for access from React application? 

            builder.Services.AddKeycloakAuthentication(configuration, o =>
            {
                o.RequireHttpsMetadata = false;
            });

            builder.Services.AddAuthorization(o =>
            {
            }).AddKeycloakAuthorization(configuration);

            // Add memory cache services
            //builder.Services.AddMemoryCache();

            builder.Services.AddControllers();
            builder.Services.AddControllersWithViews();

and app configuration: 
app.UseAuthentication();
            app.UseAuthorization();

I have 401, when I try to connect with REST API call to my Api Controller. 
How to fix that?

**Comment by TarasovK** [comment]
@VentsislavDinev 
try to add 
```
if (isDevelopmentEnvironment)
{
    services.AddHttpLogging(o =>
    {
        o.RequestHeaders.Add("Authorization");
        o.RequestHeaders.Add("Referer");
        o.ResponseHeaders.Add("WWW-Authenticate");
    });
}

and

```
if (isDevelopmentEnvironment)
{
    app.UseHttpLogging();
}
```

and check what is the reason of failed auth

**Comment by NikiforovAll** [comment]
Please feel free to contact me alexey.nikiforovall@gmail.com so we can discuss what can be done once I have more details.
