### ISSUE TITLE
VerifyTokenAudience configuration property is not applied properly.

### ISSUE THREAD

**Issue by TarasovK** [NikiforovAll/keycloak-authorization-services-dotnet#44]
The property specified in in configuration is not applied and audiece validation is still happening. I set it in both manners supported by the lib.

```
"Keycloak": {
   ... 
    "verify-token-audience": false,
    "VerifyTokenAudience": false,
    ...
  },
```

It worked only when I override it in JwtBearerOptions
```
services.AddKeycloakAuthentication(configuration, KeycloakAuthenticationOptions.Section, options =>
{
    if (isDevelopmentEnvironment)
    {
        options.RequireHttpsMetadata = false;
        options.TokenValidationParameters.ValidateAudience = false;
    }
});
```

Until I did that - I was refused with 401 with following log, while `resource` property in the configuration was not equal to the audience written in the token
```
[2023-06-08 12:20:39.652][INF][d5e614c1-ffef-4ad2-b2da-154b6889f5d6] Microsoft.AspNetCore.HttpLogging.HttpLoggingMiddleware
Response:
StatusCode: 401
WWW-Authenticate: Bearer error="invalid_token", error_description="The audience 'account' is invalid"
```

which is fine if I would do the audience validation but I would like configuration property to work as expected.

**Comment by NikiforovAll** [comment]
Could you please try to reproduce it in the latest versions? I was not able to reproduce it

**Comment by NikiforovAll** [comment]
no feedback from OP
