### ISSUE TITLE
Make Configuration use `IOptions`

### ISSUE THREAD

**Issue by kirides** [NikiforovAll/keycloak-authorization-services-dotnet#45]
The code currently assumes that all configuration sources are applied prior to adding KeycloakAuthentication/Authorization/...

This is not always the case and goes against the way other .NET components work.
By using `services.AddOptions<...>()` and things like the following, the code can be rewritten in a way that supports any order of configuration, by sacrificing minimal performance due to `serviceProvider.GetRequiredService<IOptions<..>>()`-Lookups.

```cs
// we can make use of DI for configuring JwtBearerOptions
// by registering it with the same name as the scheme itself
services.AddOptions<JwtBearerOptions>(JwtBearerDefaults.AuthenticationScheme)
    .Configure((JwtBearerOptions opts, IOptions<KeycloakAuthenticationOptions> keycloakOption)
        => { /* ... */})
// ...
services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddJwtBearer(/* JwtBearerDefaults.AuthenticationScheme */);
```

Also current `IConfiguration` overloads force `Keycloak` or any other named Key as the location for the values, as such the following appsettings could not be used with the current way:

```json
{
  "AuthServerUrl": "..."
}
```

i propose any `IConfiguration`-Overload _assumes_ that it's already at the correct location (e.g. by `configuration.GetSection("here:is:keycloak")`) and a new overload that takes in the `IConfiguration` _and_ a section name, which may be set to `null` to use default `Keycloak` section name, though this reduces the visibility of configuration sources by a bit.

----

The way the ASP.NET Core pipeline works, we can't really make use of `IOptionsSnapshot` or `IOptionsMonitor`, as the AuthenticationOptions only get applied once.

**Comment by NikiforovAll** [comment]
The a good point, added to 2.0.0 scope

**Comment by NikiforovAll** [comment]
Could you please provide an example of overload that you are talking about?

**Comment by NikiforovAll** [comment]
ref: https://github.com/NikiforovAll/keycloak-authorization-services-dotnet/issues/53

**Comment by NikiforovAll** [comment]
Added since 2.0.0-pre2
