### ISSUE TITLE
Interest In Adding Delete Endpoints?

### ISSUE THREAD

**Issue by Persistent13** [NikiforovAll/keycloak-authorization-services-dotnet#58]
Hello!

I see a distinct lack of delete endpoints and was unsure if that was on purpose. If so, feel free to let me know!

Otherwise, would there be any interest if I were to contribute some delete endpoints?
I have need to delete users using this client and have extended the SDK library privately to do so but would love to have those changes added into the main work here, if desired.

**Comment by NikiforovAll** [comment]
Hello @Persistent13

I have no objections adding delete endpoints

**Comment by Persistent13** [comment]
@NikiforovAll Here's a PR for just a delete user endpoint. I figure I'd start small until I've got the PR process nailed down then bring the rest in.

Let me know what you think and if you'd like anything changed up!

https://github.com/NikiforovAll/keycloak-authorization-services-dotnet/pull/59
