### ISSUE TITLE
Use Keycloak side by side with form login

### ISSUE THREAD

**Issue by koureasstavros** [NikiforovAll/keycloak-authorization-services-dotnet#95]
First of all, keep the nice work!

I have a Microsoft Blazor application where I have implemented a custom AuthenticationStateProvider and I am using Blazored Modal for pop up window to have login and logout forms. While trying to integrate this solution I see two problems:

1. Under the Client's MainLayout.razor I should remove the AuthorizeView which is surrounding the @Body but this has as an effect that Not Authorized users can see the views if the know the links (of course will not be capable to do something as the authorize attribute of the controllers will protect the apis).
2. Under Client's Program.cs keeping the registration of my custom authentication state provider makes the application to fail even from the start, so I wonder how to keep both ways for login, see the error below:

![image](https://github.com/NikiforovAll/keycloak-authorization-services-dotnet/assets/6669704/193c11fc-8334-4186-b75a-f74cde1a7921)

**Comment by NikiforovAll** [comment]
Hi @koureasstavros, SPA-like client applications support is out of the scope of this library.

**Comment by koureasstavros** [comment]
Hi, not sure I understand your comment. I use Microsoft Blazor Hosted WebAssembly.

**Comment by NikiforovAll** [comment]
Yes, a client application is responsible for token retrieval and the SPA scenario is not supported.
